inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '**/*.slim'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'config/routes.rb'
    - 'config/routes/**/*'
