// ========================================================================== //
// for more infomation, visit https://github.com/Huachao/vscode-restclient    //
// this vscode extension can send request from editor and get response easily //
// ========================================================================== //

# define variables here
@host_v1 = http://localhost:3000/api/v1/web/

// ========================================================================== //


// ************************************************************************** //
                     ###    ########  ##     ## #### ##    ##
                    ## ##   ##     ## ###   ###  ##  ###   ##
                  ##    ##  ##     ## #### ####  ##  ####  ##
                  ##     ## ##     ## ## ### ##  ##  ## ## ##
                  ######### ##     ## ##     ##  ##  ##  ####
                  ##     ## ##     ## ##     ##  ##  ##   ###
                  ##     ## ########  ##     ## #### ##    ##
// ************************************************************************** //

# Get available admin roles
GET {{host_v1}}admins/roles HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ

###

# get admin list
GET {{host_v1}}admins HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ

###

# get Admin list with paginate, sort, and filter options
GET {{host_v1}}admins?page[number]=1&page[size]=10&sort=-id&filter=actived HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ
###

# add a new Admin
POST {{host_v1}}admins HTTP/1.1
content-type: application/vnd.api+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ

{
  "data": {
    "type": "admins",
    "attributes": {
      "email": "test100@test.com",
      "password": "qwerasdf",
      "name": "test100",
      "role": "super"
    }
  }
}

###

# edit an Admin
PUT {{host_v1}}admins/38 HTTP/1.1
content-type: application/vnd.api+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ

{
  "data": {
    "type": "admins",
    "attributes": {
      "name": "test500",
      "role": "super"
    }
  }
}

###

# suspend an Admin
PUT {{host_v1}}admins/36/suspend HTTP/1.1
content-type: application/vnd.api+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ

###

// ************************************************************************** //
                    ##     ##  ######  ######## ########
                    ##     ## ##    ## ##       ##     ##
                    ##     ## ##       ##       ##     ##
                    ##     ##  ######  ######   ########
                    ##     ##       ## ##       ##   ##
                    ##     ## ##    ## ##       ##    ##
                    #######   ######  ######## ##     ##
// ************************************************************************** //

# get users list
GET {{host_v1}}users HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ

###

# get users list with paginate and sort options
GET {{host_v1}}users?page[number]=1&page[size]=10&sort=-id HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ

###

// ************************************************************************** //
########  ########   #######  ########  ##     ##  ######  ########     ######     ###    ######## ########  ######    #######  ########  ##    ##
##     ## ##     ## ##     ## ##     ## ##     ## ##    ##    ##       ##    ##   ## ##      ##    ##       ##    ##  ##     ## ##     ##  ##  ##
##     ## ##     ## ##     ## ##     ## ##     ## ##          ##       ##        ##   ##     ##    ##       ##        ##     ## ##     ##   ####
########  ########  ##     ## ##     ## ##     ## ##          ##       ##       ##     ##    ##    ######   ##   #### ##     ## ########     ##
##        ##   ##   ##     ## ##     ## ##     ## ##          ##       ##       #########    ##    ##       ##    ##  ##     ## ##   ##      ##
##        ##    ##  ##     ## ##     ## ##     ## ##    ##    ##       ##    ## ##     ##    ##    ##       ##    ##  ##     ## ##    ##     ##
##        ##     ##  #######  ########   #######   ######     ##        ######  ##     ##    ##    ########  ######    #######  ##     ##    ##
// ************************************************************************** //

# get all product categories
GET {{host_v1}}product_categories HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ

###

# create a product category
POST {{host_v1}}product_categories HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ
content-type: application/vnd.api+json

{
  "data": {
    "type": "product-categories",
    "attributes": {
      "name": "生活用品",
      "description": "滿足你對品味的堅持"
    }
  }
}

###

# create a sub product category
POST {{host_v1}}product_categories HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ
content-type: application/vnd.api+json

{
  "data": {
    "type": "product-categories",
    "attributes": {
      "name": "沙發",
      "description": "精選高品質真皮",
      "parent_id": "26"
    }
  }
}

###

# update a product category
PUT {{host_v1}}product_categories/26 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ
content-type: application/vnd.api+json

{
  "data": {
    "type": "product-categories",
    "attributes": {
      "name": "單椅",
      "description": "精選高品質真皮"
    }
  }
}

###

// ************************************************************************** //
 ######  #### ######## ########     ######   #######  ##    ## ######## ####  ######
##    ##  ##     ##    ##          ##    ## ##     ## ###   ## ##        ##  ##    ##
##        ##     ##    ##          ##       ##     ## ####  ## ##        ##  ##
 ######   ##     ##    ######      ##       ##     ## ## ## ## ######    ##  ##   ####
      ##  ##     ##    ##          ##       ##     ## ##  #### ##        ##  ##    ##
##    ##  ##     ##    ##          ##    ## ##     ## ##   ### ##        ##  ##    ##
 ######  ####    ##    ########     ######   #######  ##    ## ##       ####  ######
// ************************************************************************** //

# get all site configs
GET {{host_v1}}site_config HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ

###

# update meta tags config
PUT {{host_v1}}/site_config/meta_tags HTTP/1.1
content-type: application/vnd.api+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTUxOTg5NTkxMywicm9sZSI6InN1cGVyIiwidHlwZSI6IkFkbWluIiwicmVmIjoid2ViIn0.HjYEKFCiS80llONdgSLzOie4ZQ_ggRS62zwfthneWoQ

{
  "data": {
    "type": "sita-configs",
    "attributes": {
      "site_name": "AppStarter",
      "reverse": false,
      "separator": "::",
      "description": "odd Digital Design Studio application template.",
      "keywords": "web-design, web-develop"
    }
  }
}
