export_i18n_js: "app/javascript/src/locale/"
translations:
- file: 'app/javascript/src/locale/%{locale}.js'
  only: ['*.actions', '*.admin', '*.views', '*.helpers', '*.activerecord', '*.enums', '*.aasm_state', '*.page_titles', '*.devise', 'errors', '*.date', '*.datetime', '*.number', '*.support', '*.time']
