# config/app.yml for rails-settings-cached
defaults: &defaults
  product_config:
    safe_stock_level: 10
  meta_tags:
    site_name: 'AppStarter'
    reverse: false
    separator: '::'
    description: 'odd Digital Design Studio application template.'
    keywords: 'web-design, web-develop'
    type: 'website'
    locale: 'zh_TW'
  trackers:
    ignore_dnt: false
    ga: <%= ENV['ga_id'] %>
    facebook_pixel: <%= ENV['fb_pixel_id'] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
