export const SET_FLASH_MESSAGES = 'SET_FLASH_MESSAGES'
export const ADD_FLASH_MESSAGES = 'ADD_FLASH_MESSAGES'
export const CLEAR_FLASH_MESSAGES = 'CLEAR_FLASH_MESSAGES'
export const UPDATE_QUERY_STRING = 'UPDATE_QUERY_STRING'
