export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const GET_RELATED_USERS_SUCCESS = 'GET_RELATED_USERS_SUCCESS'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

export const API_REQUEST_START = 'API_REQUEST_START'
export const API_REQUEST_FAIL = 'API_REQUEST_FAIL'
